version: 2
workflows:
  version: 2
  build:
    jobs:
    - verify
jobs:
  verify:
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - run:
        command: echo "This is the new-name project, but renamed as old-name, now re-followed"
