version: 2
workflows:
  version: 2
  build:
    jobs:
    - verify: {}
jobs:
  verify:
    description: Runs simple or blue/green deployments to Cloud Foundry.
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - run:
        command: echo "This is the new-name project"
